#!/bin/bash

set -e

if [[ -z $RUDRA_RUNNER_HOME ]]; then
    echo '$RUDRA_RUNNER_HOME is not set'
    exit 1
fi

docker run -t --rm --user "$(id -u)":"$(id -g)" -v "$RUDRA_RUNNER_HOME":/tmp/rudra-runner-home \
  --env RUDRA_RUNNER_HOME=/tmp/rudra-runner-home -v "$PWD":/tmp/rudra -w /tmp/rudra rudra:latest rudra-runner
