#!/bin/bash

# First argument: target directory
# Second argument: report directory

set -e

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <target_dir> [report_path]"
    echo 'Please provide the target directory as an argument'
    exit 1
fi

if [[ ! -d $1 ]]; then
    echo "$1 is not a directory"
    exit 1
fi

if [[ -z $RUDRA_RUNNER_HOME ]]; then
    echo '$RUDRA_RUNNER_HOME is not set'
    exit 1
fi

if [[ -z $RUSTUP_TOOLCHAIN ]]; then
    RUSTUP_TOOLCHAIN="nightly-2020-08-26"
fi

if [[ -n $2 ]]; then
    echo "[*] Creating report directory at $2"
    mkdir $2
    ABS_PATH=$(realpath $2)
    DOCKER_ARGS+=" -v $ABS_PATH:/tmp/report --env RUDRA_REPORT_PATH=/tmp/report/report"
fi

docker run -t --rm --user "$(id -u)":"$(id -g)" -v "$RUDRA_RUNNER_HOME":/tmp/rudra-runner-home \
    ${DOCKER_ARGS} \
    --env CARGO_HOME=/tmp/rudra-runner-home/cargo_home \
    --env SCCACHE_DIR=/tmp/rudra-runner-home/sccache_home --env SCCACHE_CACHE_SIZE=10T \
    --env RUSTUP_TOOLCHAIN="$RUSTUP_TOOLCHAIN" \
    -v "$(realpath $1)":/tmp/rudra -it -w /tmp/rudra rudra:latest cargo rudra ${CARGO_ARGS}
