#!/bin/bash

set -e

if [[ -z $RUDRA_RUNNER_HOME ]]; then
    echo '$RUDRA_RUNNER_HOME is not set'
    exit 1
fi

if [[ -z $RUDRA_RUSTUP_TOOLCHAIN ]]; then
    RUDRA_RUSTUP_TOOLCHAIN="nightly-2021-08-20"
fi

docker run -it --rm --user "$(id -u)":"$(id -g)" -v "$RUDRA_RUNNER_HOME":/tmp/rudra-runner-home \
  --env CARGO_HOME=/tmp/rudra-runner-home/cargo_home \
  --env SCCACHE_DIR=/tmp/rudra-runner-home/sccache_home --env SCCACHE_CACHE_SIZE=10T \
  --env RUSTUP_TOOLCHAIN="$RUDRA_RUSTUP_TOOLCHAIN" \
  --env RUDRA_RUNNER_HOME=/tmp/rudra-runner-home rudra-artifact:latest
