name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache toolchain
      uses: actions/cache@v2
      env:
        cache-name: cache-rust-toolchain
      with:
        path: ~/.rustup/toolchains
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('ci/setup_toolchains.sh') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Setup toolchains
      run: ci/setup_toolchains.sh

    - name: Build
      run: ci/build.sh

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tomlkit

    - name: Cache cargo-download
      uses: actions/cache@v2
      env:
        cache-name: cache-cargo-download
      with:
        path: ~/.cargo/bin/cargo-download
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Run tests
      run: ci/test.sh
